// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpXRYz_A1b2u-G-uiarCzu1_5YD4Kdwuw',
    appId: '1:741934541433:web:b7ab717d197abbfaf042a8',
    messagingSenderId: '741934541433',
    projectId: 'ruscacepte',
    authDomain: 'ruscacepte.firebaseapp.com',
    storageBucket: 'ruscacepte.firebasestorage.app',
    measurementId: 'G-L5DGKKYGNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiu0vdNUFkKA80a7HFDP-Y0OrOhc7vfeQ',
    appId: '1:741934541433:android:d30ffd0ae8e3461bf042a8',
    messagingSenderId: '741934541433',
    projectId: 'ruscacepte',
    storageBucket: 'ruscacepte.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8w_VjhDUKayW6RkM8ubbJItdfbezEXzA',
    appId: '1:741934541433:ios:eee4d3c209d09fd8f042a8',
    messagingSenderId: '741934541433',
    projectId: 'ruscacepte',
    storageBucket: 'ruscacepte.firebasestorage.app',
    iosBundleId: 'com.example.ruscacebimde',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8w_VjhDUKayW6RkM8ubbJItdfbezEXzA',
    appId: '1:741934541433:ios:eee4d3c209d09fd8f042a8',
    messagingSenderId: '741934541433',
    projectId: 'ruscacepte',
    storageBucket: 'ruscacepte.firebasestorage.app',
    iosBundleId: 'com.example.ruscacebimde',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpXRYz_A1b2u-G-uiarCzu1_5YD4Kdwuw',
    appId: '1:741934541433:web:80667cba11077f73f042a8',
    messagingSenderId: '741934541433',
    projectId: 'ruscacepte',
    authDomain: 'ruscacepte.firebaseapp.com',
    storageBucket: 'ruscacepte.firebasestorage.app',
    measurementId: 'G-8EH6PQ52D3',
  );
}
